version: "3.8"

services:
  fee-api:
    build: fee_api
    ports:
      - "4000:4000"
    environment:
      - RAILS_ENV=production
      - PG_DATABASE_URL=postgres://advoc:advoc@postgres-db:5432/advoc
      - MONGODB_DATABASE_URL=mongodb://advoc:advoc@mongodb-db:27017/advoc
    depends_on:
      - postgres-db
    networks:
      - advoc_network
  
  front-end:
    build: advocates
    ports:
      - "3000:80"
    depends_on:
      - fee-api
    networks:
      - advoc_network

  mongo_db:
    build: database/mongodb
    container_name: mongo_advoc_db
    ports:
      - "27019:27017"

  postgres-db:
    build: database/postgresql
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=advoc
      - POSTGRES_USER=advoc
      - POSTGRES_PASSWORD=advoc
    volumes:
      - $HOME/fee_api/data/postgres:/var/lib
    networks:
      - advoc_network

networks:
  advoc_network: {}
