# Use the official PostgreSQL image from Docker Hub
FROM postgres:latest

# Set environment variables
ENV POSTGRES_DB advoc
ENV POSTGRES_USER advoc
ENV POSTGRES_PASSWORD advoc

# Expose the default PostgreSQL port (5432)
EXPOSE 5432